### ISSUE TITLE
.NET Framework 4.5

### ISSUE THREAD

**Issue by heldermrgoncalves** [cake-contrib/Cake.Newman#1]
Hi!

Is there any reason why .NET 4.5 is not supported?

When building my cake script, I'm getting the following error:

```
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Cake.Core.CakeException: Failed to install addin 'Cake.Newman'.
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(ScriptAnalyzerResult analyzerResult, DirectoryPath installPath)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
Process terminated with code 1.
```

I've followed your blog post [here](https://blog.agchapman.com/announcing-cake-newman/) and added the following to my cake.script:

```
// Top of file
#addin "Cake.Npm"
#addin "Cake.Newman"

// inside Setup
Npm.Install(settings => settings.Package("newman").Globally());

// inside Task
RunCollection("./collection.json");
```

Any suggestions? :)

Thanks!

**Comment by gep13** [comment]
@agc93 is based in Australia, and likely sleeping just now, but I am sure that he will take a look when he can.

Is this on a public repo?  i.e. so that we can try to reproduce it?

**Comment by agc93** [comment]
Ah, I think I know what's causing this one!

I'll test my fix tonight and get an update as soon as I can.

**Comment by heldermrgoncalves** [comment]
The repository is private.

I believe this is because [Cake.Newan](https://www.nuget.org/packages/Cake.Newman) is only available for .NET 4.5.1 and .NET Standard 1.6 from looking at the file structure:

![image](https://cloud.githubusercontent.com/assets/3136241/22326333/1ee27b9e-e3aa-11e6-9ae2-1b5d2d8e0a3e.png)

Thanks for the quick reply @agc93

**Comment by agc93** [comment]
Yeah, I just need to switch the TFM and `project.json` over to `net45` and that *should* fix it..

**Comment by agc93** [comment]
Okay @heldermrgoncalves there's a new prerelease version on NuGet now (0.1.0-unstable0004).

Can you try changing the line to:

```csharp
#addin nuget:?package=Cake.Newman&version=0.1.0-unstable0004
```

and testing again (you may need to also clear your `tools` directory)?

**Comment by heldermrgoncalves** [comment]
@agc93

I'm getting this error now:

```
run indicators_collection.json
Executing: "C:/Program Files (x86)/Microsoft Visual Studio 14.0/Web/External/newman" run indicators_collection.json
----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Finished running tasks.
An error occurred when executing task '__Test'.
Error: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Cake.Core.IO.ProcessRunner.Start(FilePath filePath, ProcessSettings settings)
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments)
   at Submission#0.<.ctor>b__19()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass5_0.<Does>b__0(ICakeContext context)
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

I'm running on Windows 10 Home - 64 Bit

Any ideas? :|

**Comment by agc93** [comment]
Hmmm, what is that `"C:/Program Files (x86)/Microsoft Visual Studio 14.0/Web/External/newman"` file? I've never used Newman as part of VS before? What happens if you just run that as `newman -v`?

Looks to me like that is a problem with your newman install/executable...

**Comment by AaronMorgan** [comment]
I'm getting the same behaviour (but without the exception stack). My Cake.Build is the same as @heldermrgoncalves with the addition of using:

> version=0.1.0-unstable0004

**Comment by agc93** [comment]
Can either @AaronMorgan or @heldermrgoncalves please run your build script with verbosity set to Diagnostic and upload the file here (or a Gist) so I can see what's going on? I just tried a minimal sample with the new package and it works fine.

**Comment by AaronMorgan** [comment]
Thanks @agc93, output attached, it's the last 1000 lines. If not enough please let me know.

[build_output.txt](https://github.com/cake-contrib/Cake.Newman/files/734431/build_output.txt)

**Comment by agc93** [comment]
Hmmm, I might need to look into this as I can't easily see if that error is coming back from the call to `npm` or to `newman` or some combination. I'll try and spin up a clean workstation and test it out tonight.

**Comment by agc93** [comment]
Okay I have isolated the issue, but the fix *might* break it for non-Windows systems. I need to do some testing on Linux tonight and I will hopefully have another fix package out in the next 24 hours.

---

*More info:*

From what I can tell, it looks like the `npm install` operation installs two files: `newman.cmd` and `newman` into the bin path. Since `newman` takes priority (from [here](https://github.com/agc93/Cake.Newman/blob/master/src/Cake.Newman/NewmanRunner.cs#L27)), that gets picked up, but that is a shell script. We could switch the priority around but then you'll just be executing a `.cmd` on Linux, with likely similar results to your issue.

**Comment by agc93** [comment]
@AaronMorgan @heldermrgoncalves 

There's **another** prerelease up on NuGet now: `0.1.0-unstable0006` now which should solve the problem on Windows machines. I still need to test it a bit more on Linux before I release as a stable package but if you can try again with the new package and let me know if it works, that would be really helpful..

**Comment by AaronMorgan** [comment]
@agc93 Thanks that's fixed the issue., cheers.

**Comment by agc93** [comment]
Thanks for all the feedback @AaronMorgan and @heldermrgoncalves !

NuGet has been updated with [version 0.2.0](https://www.nuget.org/packages/Cake.Newman/0.2.0) which resolves the issues with locating the correct `newman` executable (and therefore this issue). Let me know if you see any more problems!
